### ISSUE TITLE
Tir dans la rue

### ISSUE THREAD

**Issue by kossolax** [kossolax/TSX-RP#246]
Même principe que agression + ces 2 events là:

https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#weapon_fire
https://wiki.alliedmods.net/Counter-Strike:_Global_Offensive_Events#bullet_impact

avec un exemple sur "comment récupéré un événement du jeu": https://forums.alliedmods.net/showthread.php?p=2352351#post2352351

**Comment by Hellhium** [comment]
https://wiki.alliedmods.net/Events_(SourceMod_Scripting)#Post_Hooks
