### ISSUE TITLE
Doublon Mcdo

### ISSUE THREAD

**Issue by messoremTsX** [kossolax/TSX-RP#364]
Sauf erreur, l'hamburger énergie et le Redbull ont exactement le même effet soit 100% d’énergie.
L'hamburger coûte 100 et le redbull 30....

**Comment by kossolax** [comment]
redbull cd 5 secondes
energy cd 1 seconde (et 20hp de gagné)

2016-11-23 22:43 GMT+01:00 Messorem notifications@github.com:
