### ISSUE TITLE
Numero zone appart

### ISSUE THREAD

**Issue by Hellhium** [kossolax/TSX-RP#42]
Il faudrait une fonction qui à un numéro d'appartement associe le numéro de la zone qui lui correspond

**Comment by kossolax** [comment]
char tmp[32];
rp_GetZoneData(id, zone_type_type, tmp, sizeof(tmp));
tmp --> appart_38

Plus qu'à boucler pour trouver quel zone correspond. (attention de pas
spam la recherche de "appartToZoneID" partout)
